### PR TITLE
chore: Uses VCT test tree for BDD tests

### PR DESCRIPTION
**Pull request by soluchok**
Signed-off-by: Andrii Soluk <isoluchok@gmail.com>

### CODE REVIEW

**Review by fqutishat — CHANGES_REQUESTED** [review]
Bdd test should not use any mocking

**Comment by soluchok** [comment]
> Bdd test should not use any mocking

@fqutishat  It is not mock. 
`VCT_TEST_TREE=true` is equal to `./createtree --admin_server=9090`
VCT_TEST_TREE automatically creates a log id using Trillian sdk. 
The log id is created with the default configuration. 
It is helpful when we just want to run a service with the default configuration (e.g for tests).
For real usage (e.g prod) you would need to create the log id separately. And run the service with that id or an existing id (e.g created a long time ago). 
You can use `VCT_TEST_TREE` for production but it is not correct. If the service fails it would create a new log id every time the service is up again. The log id should be created and handled outside the service.

@troyronda `In prod, new logs will be created on a regular basis ... as many cert transparency services do - Eg yearly.`

**Comment by troyronda** [comment]
Would it make more sense to have a separate CLI command for this?

**Comment by soluchok** [comment]
> Would it make more sense to have a separate CLI command for this? (To create log)

@troyronda I assume sooner or later we will fork `createtree` (or copy the code) at least to add support for PostgreSQL and probably KMS. It will be a separate cli. For now, we can use `createtree` from the Trillian (or with VCT_TEST_TREE=true). The change I did is just to simplify the usage of the BDD tests (especially when you work with it locally with `DISABLE_COMPOSITION=true` ).

NOTE: `VCT_TEST_TREE` can be renamed to `VCT_CREATE_TREE`. Probably it will not be so confusing.

**Comment by soluchok** [comment]
> Would it make more sense to have a separate CLI command for this? (To create log)

@troyronda just realized that 

> > Would it make more sense to have a separate CLI command for this? (To create log)
> 
> @troyronda I assume sooner or later we will fork `createtree` (or copy the code) at least to add support for PostgreSQL and probably KMS. It will be a separate cli. For now, we can use `createtree` from the Trillian (or with VCT_TEST_TREE=true). The change I did is just to simplify the usage of the BDD tests (especially when you work with it locally with `DISABLE_COMPOSITION=true` ).
> 
> NOTE: `VCT_TEST_TREE` can be renamed to `VCT_CREATE_TREE`. Probably it will not be so confusing.

@troyronda  just realized that `createtree` does not depend on DB. So, we can reuse the original cli (createtree`). Not sure whether we need a new one. Probably, if we need some customization or just to keep everything in one place.

**Review by bstasyszyn — APPROVED** [review]

**Pull request closed without merging**
